---
title: "Bing Maps on Azure Marketplace | Microsoft Docs"
ms.custom: ""
ms.date: "08/31/2020"
ms.reviewer: ""
ms.suite: ""
ms.tgt_pltfrm: ""
ms.topic: "home-page"
ms.assetid: ""
caps.latest.revision: ""
author: "DRMap"
ms.author: "dirabel"
manager: "donnali"
ms.service: "bing-maps"
---
